CREATE DATABASE LOAN_MANAGEMENT_SYSTEM;
USE LOAN_MANAGEMENT_SYSTEM;
-- -------------------------------------------------------------------------
-- QUESTION     										-- harish
/*Sheet 1
•Import table from sheet 1- customer income status*/

-- OUTPUT
SELECT * FROM CUSTOMER_INCOME;
-- -------------------------------------------------------------------------
-- QUESTION
/*•	set customer criteria based on applicant income
Criteria
•	Applicant income >15,000 = grade a
•	Applicant income >9,000 = grade b
•	Applicant income >5000 = middle class customer
•	Otherwise low class
(Create this as new table)*/

-- QUERY
CREATE TABLE SALARY_CRITERIA1
SELECT *,
CASE
WHEN APPLICANTINCOME>15000 THEN 'GRADE A'
WHEN APPLICANTINCOME>9000 THEN 'GRADE B'
WHEN APPLICANTINCOME>5000 THEN 'MIDDLE CLASS CUSTOMER'
ELSE 'LOW CLASS'
END AS GRADE
FROM CUSTOMER_INCOME;

-- OUTPUT 
SELECT * FROM SALARY_CRITERIA1;
DROP TABLE SALARY_CRITERIA1;
-- ---------------------------------------------------------------------------------
-- QUESTION
/*Monthly interest percentage 
Criteria
•	Applicant income <5000 rural=3%
•	Applicant income <5000 semi rural=3.5%
•	Applicant income <5000 urban=5%
•	Applicant income <5000 semi urban= 2.5%
•	Otherwise =7%*/


-- QUERY
CREATE TABLE SALARY_CRITERIA2
SELECT *,
CASE 
WHEN APPLICANT_INCOME<5000 AND PROPERTY_AREA='RURAL'THEN'3%'
WHEN APPLICANT_INCOME<5000 AND PROPERTY_AREA='SEMIRURAL'THEN'3.5%'
WHEN APPLICANT_INCOME<5000 AND PROPERTY_AREA='URBAN'THEN'5%'
WHEN APPLICANT_INCOME<5000 AND PROPERTY_AREA='SEMIURBAN'THEN'2.5%'
ELSE '7%'
END AS MONTHLY_INT_PERCENTAGE
FROM CUSTOMER_INCOME;



-- OUTPUT
SELECT * FROM SALARY_CRITERIA2;
-- ----------------------------------------------------------------------------------
-- QUESTION															-- mohamed shahil
/*New field creation based on interest
•Calculate monthly interest amt and annual interest
 amt based on loan amt*/


SELECT * FROM CIBIL_SCORE_STATUS; -- LEFT TABLE
SELECT * FROM SAL_CRITERIA2; -- RIGHT TABLE

CREATE TABLE CUSTOMER_INTREST;
SELECT S.*,C.LOANAMOUNT,C.LOAN_AMOUNT_TERM,C.`CIBIL SCORE`,C.CIBIL_STATUS 
FROM
SAL_CRITERIA2 AS S RIGHT JOIN CIBIL_SCORE_STATUS AS C
ON S.LOAN_ID = C.LOAN_ID;
SELECT * FROM CUSTOMER_INTREST;
 
-- QUERY
CREATE TABLE SALARY_CRITERIA3 ;
 SELECT LOAN_ID,
 CASE 
 WHEN MONTHLY_PERCENTAGE = "7%" THEN  (LOANAMOUNT*7/100)
 WHEN MONTHLY_PERCENTAGE = "3%" THEN  (LOANAMOUNT*3/100)
 WHEN MONTHLY_PERCENTAGE = "3.5%" THEN  (LOANAMOUNT*3.5/100)
 WHEN MONTHLY_PERCENTAGE = "5%" THEN  (LOANAMOUNT*5/100)
 WHEN MONTHLY_PERCENTAGE = "2.5%" THEN  (LOANAMOUNT*2.5/100)
 END AS MONTHLY_INT_AMT,
 CASE
 WHEN MONTHLY_PERCENTAGE = "7%" THEN (LOANAMOUNT*7/100*12)
 WHEN MONTHLY_PERCENTAGE = "3%" THEN  (LOANAMOUNT*3/100*12)
 WHEN MONTHLY_PERCENTAGE = "3.5%" THEN  (LOANAMOUNT*3.5/100*12)
 WHEN MONTHLY_PERCENTAGE = "5%" THEN  (LOANAMOUNT*5/100*12)
 WHEN MONTHLY_PERCENTAGE = "2.5%" THEN  (LOANAMOUNT*2.5/100*12)
 END AS ANNUAL_INT_AMT
 FROM CUSTOMER_INTREST;
 
 
 ALTER TABLE SALARY_CRITERIA3 MODIFY ANNUAL_INT_AMT DOUBLE(10,2);
 
 -- OUTPUT
 SELECT * FROM SALARY_CRITERIA3;
-- -------------------------------------------------------------------------------
 -- QUESTION
 /*•	Create all the above fields as a table 
   •	Table name - customer interest analysis
(create this into a new table and connect with sheet 2 (loan status) bring the output)*/
 
 
 -- QUERY  --using full outer join
CREATE TABLE  CUSTOMER_INTEREST_ANALYSIS
(SELECT S.*,S3.LOANAMOUNT,S3.MONTHLY_PERCENTAGE,S3.MONTHLY_INT_AMT,ANNUAL_INT_AMT
FROM
SALARY_CRITERIA S LEFT JOIN SALARY_CRITERIA3 S3
ON S.LOAN_ID = S3.LOAN_ID)
UNION
(SELECT S.*,S3.LOANAMOUNT,S3.MONTHLY_PERCENTAGE,S3.MONTHLY_INT_AMT,ANNUAL_INT_AMT
FROM
SALARY_CRITERIA S RIGHT JOIN SALARY_CRITERIA3 S3
ON S.LOAN_ID = S3.LOAN_ID);


-- OUTPUT
 SELECT * FROM CUSTOMER_INTEREST_ANALYSIS;	
-- --------------------------------------------------------------------------------
-- QUESTION																-- Guru Pandi
/*Sheet 2 - loan status
•	Create row level trigger for loan amt 
Criteria
•	Loan amt null = loan still processing
*/


-- QUERY
 CREATE TABLE LOAN_STATUS (LOAN_ID VARCHAR(30),
 CUSTOMER_ID VARCHAR(50),
 LOANAMOUNT VARCHAR(50),
 LOAN_AMOUNT_TERM INT,
 `CIBIL SCORE` INT);
 
 
 SELECT * FROM LOAN_STATUS;
 DROP TABLE LOAN_STATUS;
 DROP TRIGGER  LOAN_AMT_CRITERIA;
 
 
 DESCRIBE LOAN_STATUS;
   
 DELIMITER //
 CREATE TRIGGER LOAN_AMT_CRITERIA
 BEFORE INSERT 
 ON 
 LOAN_STATUS FOR EACH ROW
 BEGIN
 IF 
 NEW.LOANAMOUNT IS NULL THEN SET NEW.LOANAMOUNT = "LOAN STILL PROCESSING";
 END IF;
 END //
 DELIMITER ;


-- OUTPUT
SELECT * FROM LOAN_STATUS;
INSERT INTO LOAN_STATUS SELECT * FROM LOAN_STAT;


-- ------------------------------------------------------------------------------
-- QUESTION
/*	•	Create statement level trigger for cibil score
Criteria 
•	Cibil score >900 high cibil score
•	Cibil score >750 no penalty
•	Cibil score >0 penalty customers
•	Cibil score <=0 reject customers (loan cannot apply)
*Then delete the reject and loan still processing customers*/

-- QUERY
-- STATEMENT LEVEL TRIGGER
CREATE TABLE CIBIL_SCORE_STATUS (
LOAN_ID VARCHAR(50),
CUSTOMER_ID VARCHAR(50),
LOANAMOUNT VARCHAR(50),
LOAN_AMOUNT_TERM INT,
`CIBIL SCORE` INT,
CIBIL_STATUS VARCHAR(50)
);



-- STATEMENT LEVEL TRIGGER
DELIMITER //
CREATE TRIGGER CIBIL_CRITERIA
AFTER INSERT 
ON 
LOAN_STATUS FOR EACH ROW
BEGIN
IF
NEW.`CIBIL SCORE`  >900 THEN
INSERT INTO CIBIL_SCORE_STATUS(LOAN_ID ,CUSTOMER_ID ,LOANAMOUNT ,LOAN_AMOUNT_TERM ,`CIBIL SCORE`,CIBIL_STATUS)
VALUES (NEW.LOAN_ID ,NEW.CUSTOMER_ID ,NEW.LOANAMOUNT ,NEW.LOAN_AMOUNT_TERM ,NEW.`CIBIL SCORE`,"HIGH CIBIL SCORE");
ELSEIF
NEW.`CIBIL SCORE`  >750 THEN
INSERT INTO CIBIL_SCORE_STATUS(LOAN_ID ,CUSTOMER_ID ,LOANAMOUNT ,LOAN_AMOUNT_TERM ,`CIBIL SCORE`,CIBIL_STATUS)
VALUES (NEW.LOAN_ID ,NEW.CUSTOMER_ID ,NEW.LOANAMOUNT ,NEW.LOAN_AMOUNT_TERM ,NEW.`CIBIL SCORE`,"NO PENALTY");
ELSEIF
NEW.`CIBIL SCORE`  >0 THEN
INSERT INTO CIBIL_SCORE_STATUS(LOAN_ID ,CUSTOMER_ID ,LOANAMOUNT ,LOAN_AMOUNT_TERM ,`CIBIL SCORE`,CIBIL_STATUS)
VALUES (NEW.LOAN_ID ,NEW.CUSTOMER_ID ,NEW.LOANAMOUNT ,NEW.LOAN_AMOUNT_TERM ,NEW.`CIBIL SCORE`,"PENALTY CUSTOMER");
ELSEIF
NEW.`CIBIL SCORE`  <=0 THEN
INSERT INTO CIBIL_SCORE_STATUS(LOAN_ID ,CUSTOMER_ID ,LOANAMOUNT ,LOAN_AMOUNT_TERM ,`CIBIL SCORE`,CIBIL_STATUS)
VALUES (NEW.LOAN_ID ,NEW.CUSTOMER_ID ,NEW.LOANAMOUNT ,NEW.LOAN_AMOUNT_TERM ,NEW.`CIBIL SCORE`,"REJECTED CUSTOMER");
END IF;
DELETE FROM CIBIL_SCORE_STATUS WHERE CIBIL_STATUS = "REJECTED CUSTOMER";
DELETE FROM CIBIL_SCORE_STATUS WHERE LOANAMOUNT = "LOAN STILL PROCESSING"; 
END //
DELIMITER ;

ALTER TABLE CIBIL_SCORE_STATUS MODIFY LOANAMOUNT VARCHAR(50);

-- DUMMY TABLE DATAS
SELECT * FROM LOAN_STAT;
-- INERTING LOAN_STAT TO LOAN_STATUS
INSERT INTO LOAN_STATUS SELECT * FROM LOAN_STAT;


-- OUTPUT
SELECT * FROM CIBIL_SCORE_STATUS;

DROP TRIGGER LOAN_AMT_CRITERIA;
DROP TRIGGER CIBIL_CRITERIA;

TRUNCATE CIBIL_SCORE_STATUS;
TRUNCATE LOAN_STATUS;
-- ------------------------------------------------------------------------------
-- QUESTION
/* *Update loan as integers*/


-- QUERY
ALTER TABLE CIBIL_SCORE_STATUS MODIFY LOANAMOUNT INT ;


-- OUTPUT
DESCRIBE CIBIL_SCORE_STATUS; 
-- --------------------------------------------------------------------------------
-- QUESTION
/*Create all the above fields as a table */
-- QUERY
CREATE TABLE INTREST_CIBIL1
(SELECT CI.LOAN_ID,CI.`CUSTOMER ID`,CI.APPLICANTINCOME,CI.COAPPLICANTINCOME,CI.LoanAmount,CI.Monthly_Percentage,CI.Monthly_Int_Amt,CI.Annual_Int_Amt,
CI.Property_Area,CI.Loan_Status,CI.GRADE,
CS.LOAN_AMOUNT_TERM,CS.`CIBIL SCORE`,CS.CIBIL_STATUS
FROM 
CUSTOMER_INTEREST_ANALYSIS CI 
INNER JOIN 
 CIBIL_SCORE_STATUS CS
 ON 
 CI.`CUSTOMER ID` = CS.CUSTOMER_ID);


-- OUTPUT
 -- CIBIL_SCORE_STATUS
SELECT * FROM INTREST_CIBIL1;


-- TABLE 3&4 (SHEET 3 & IMORTED FILE TABLE 4 COMBINED) 
-- CUSTOMER_INFO && COUNTY_STATE

-- QUERY
CREATE TABLE CUSTOMER_COUNTRY1;
(SELECT 
 CU.CUSTOMER_ID,CU.CUSTOMER_NAME,CU.GENDER,CU.AGE,CU.MARRIED
 ,CU.EDUCATION,CU.SELF_EMPLOYED,CU.LOAN_ID,CU.REGION_ID,CO.Postal_Code,CO.SEGMENT,CO.STATE
 FROM
 CUSTOMER_INFO CU inner JOIN COUNTRY_STATE CO
 ON 
 CU.CUSTOMER_ID = CO.CUSTOMER_ID);

-- QUESTION
 /*Table name - loan cibil score status details*/
 


-- QUERY
CREATE TABLE CUS_LOAN
SELECT
-- 1 
CC.CUSTOMER_ID,CC.CUSTOMER_NAME,
CC.GENDER,CC.AGE,
CC.MARRIED,CC.EDUCATION,
CC.SELF_EMPLOYED,
CC.REGION_ID,
CC.POSTAL_CODE,CC.SEGMENT,
CC.STATE,
-- 2
IC.PROPERTY_AREA,IC.LOAN_ID,
IC.APPLICANTINCOME,IC.`CIBIL SCORE`,
IC.CIBIL_STATUS,IC.COAPPLICANTINCOME,
IC.LOANAMOUNT,IC.LOAN_AMOUNT_TERM,
IC.MONTHLY_PERCENTAGE,
IC.MONTHLY_INT_AMT,
IC.ANNUAL_INT_AMT,
IC.GRADE,IC.LOAN_STATUS 
FROM 
INTREST_CIBIL1 IC INNER JOIN CUSTOMER_COUNTRY1 CC 
ON IC.`CUSTOMER ID`= CC.CUSTOMER_ID;

-- JOIN CUS AND LOAN
SELECT * FROM CUS_LOAN;  


CREATE TABLE LOAN_CIBIL_SCORE_DETAILS(
SELECT 
   CL.*,
   R.REGION
FROM 
CUS_LOAN CL INNER JOIN REGION R
ON 
CL.REGION_ID = R.REGION_ID);

-- OUTPUT (JOINT 3 TABLES CUS,LOAN,REG)
SELECT * FROM LOAN_CIBIL_SCORE_DETAILS;
-- --------------------------------------------------------------------------------
-- QUESTION																	-- karthick
/* Sheet 3 - customer info
*Import the table*/
SELECT * FROM CUSTOMER_INFO;
/**Update gender and age based on customer id */


-- QUERY
-- CHANGE MALE TO CUSTOMER_ID
UPDATE CUSTOMER_INFO SET GENDER = 'MALE'
WHERE `CUSTOMER ID` IN ('IP43018','IP43038');
-- CHANGE FEMALE TO CUSTOMER_ID
UPDATE CUSTOMER_INFO SET GENDER = 'FEMAIL'
WHERE `CUSTOMER ID`  IN ('IP43006','IP43016','IP43508','IP43577','IP43589','IP43593');
-- CHANGE AGE TO CUSTOMER_ID
UPDATE CUSTOMER_INFO SET AGE = 45 WHERE `CUSTOMER ID`= 'IP43007';
UPDATE CUSTOMER_INFO SET AGE = 32 WHERE `CUSTOMER ID`= 'IP43009'; 
 

-- OUTPUT
SELECT * FROM CUSTOMER_INFO;
-- --------------------------------------------------------------------------------------------------------------------------------
-- QUESTION															-- krishna
/* Sheet 4 and 5- country state and region
*Import the table */


-- QUERY && OUTPUTS
-- 1 TABLE (SHEET1)
SELECT * FROM CUSTOMER_INTEREST_ANALYSIS;
-- 2 TABLE (SHEET2)
SELECT * FROM CIBIL_SCORE_STATUS;
-- 3 TABLE (SHEET3)
SELECT * FROM CUSTOMER_INFO;
-- 4 TABLE(COUNTRY_STATE IMPORT FROM FILES)
SELECT * FROM COUNTRY_STATE;
-- 5 TABLE (REGION IMPORT FROM FILES)
SELECT * FROM REGION;



-- QUERY
-- SHEET 4&5 
-- OUT PUT 1 
-- JOINED 5 TABLE AS 1
SELECT * FROM CUSTOMER_LOAN_DETAILS;


-- TABLE 1&2 (SHEET 1 & 2 COMBINED)
-- CUSTOMER_INTEREST_ANALYSIS &&  CIBIL_SCORE_STATUS

-- QUERY
CREATE TABLE INTREST_CIBIL1
(SELECT CI.LOAN_ID,CI.`CUSTOMER ID`,CI.APPLICANTINCOME,CI.COAPPLICANTINCOME,CI.LoanAmount,CI.Monthly_Percentage,CI.Monthly_Int_Amt,CI.Annual_Int_Amt,
CI.Property_Area,CI.Loan_Status,CI.GRADE,
CS.LOAN_AMOUNT_TERM,CS.`CIBIL SCORE`,CS.CIBIL_STATUS
FROM 
CUSTOMER_INTEREST_ANALYSIS CI 
INNER JOIN 
 CIBIL_SCORE_STATUS CS
 ON 
 CI.`CUSTOMER ID` = CS.CUSTOMER_ID);


-- OUTPUT
 -- CIBIL_SCORE_STATUS
SELECT * FROM INTREST_CIBIL1;


-- TABLE 3&4 (SHEET 3 & IMORTED FILE TABLE 4 COMBINED) 
-- CUSTOMER_INFO && COUNTY_STATE

-- QUERY
CREATE TABLE CUSTOMER_COUNTRY1;
(SELECT 
 CU.CUSTOMER_ID,CU.CUSTOMER_NAME,CU.GENDER,CU.AGE,CU.MARRIED,CU.EDUCATION,CU.SELF_EMPLOYED,CU.LOAN_ID,CU.REGION_ID,CO.Postal_Code,CO.SEGMENT,CO.STATE
 FROM
 CUSTOMER_INFO CU inner JOIN COUNTRY_STATE CO
 ON 
 CU.CUSTOMER_ID = CO.CUSTOMER_ID);


-- OUTPUT
SELECT * FROM CUSTOMER_COUNTRY1;




-- REGION && CUSTOMER_COUNTRY1(3&4);

-- QUERY
CREATE TABLE REGION1; 
 SELECT CC.*,R.REGION FROM
 CUSTOMER_COUNTRY1 CC INNER JOIN REGION R 
 ON CC.REGION_ID = R.REGION_ID;
 
 
 -- COMBINED INNER JOIN TABLE 1&2
 
 SELECT * FROM REGION1;  -- 34 5 -
 SELECT * FROM INTREST_CIBIL1; -- 12 
 SELECT * FROM CUSTOMER_COUNTRY1; -- 34
 
 
CREATE TABLE CUS_LOAN; 
SELECT
-- 1 
CC.CUSTOMER_ID,CC.CUSTOMER_NAME,
CC.GENDER,CC.AGE,
CC.MARRIED,CC.EDUCATION,
CC.SELF_EMPLOYED,
CC.REGION_ID,
CC.POSTAL_CODE,CC.SEGMENT,
CC.STATE,
-- 2
IC.PROPERTY_AREA,IC.LOAN_ID,
IC.APPLICANTINCOME,IC.`CIBIL SCORE`,
IC.CIBIL_STATUS,IC.COAPPLICANTINCOME,
IC.LOANAMOUNT,IC.LOAN_AMOUNT_TERM,
IC.MONTHLY_PERCENTAGE,
IC.MONTHLY_INT_AMT,
IC.ANNUAL_INT_AMT,
IC.GRADE,IC.LOAN_STATUS 
FROM 
INTREST_CIBIL1 IC INNER JOIN CUSTOMER_COUNTRY1 CC 
ON IC.`CUSTOMER ID`= CC.CUSTOMER_ID;


-- COMBINED INNER JOIN TABLE 3 & CUSLOAN

CREATE TABLE CUSTOMER_LOAN_DETAILS;
SELECT 
    CL.CUSTOMER_ID,
    CL.CUSTOMER_NAME,
    CL.GENDER,
    CL.AGE,
    CL.MARRIED,
    CL.EDUCATION,
    CL.SELF_EMPLOYED,
    CL.REGION_ID,
    
    R.REGION,
    
    CL.POSTAL_CODE,
    CL.SEGMENT,
    CL.STATE,
    CL.PROPERTY_AREA,
    CL.LOAN_ID,
    CL.APPLICANTINCOME,
    CL.`CIBIL SCORE`,
    CL.CIBIL_STATUS,
    CL.COAPPLICANTINCOME,
    CL.LOANAMOUNT,
    CL.LOAN_AMOUNT_TERM,
    CL.MONTHLY_PERCENTAGE,
    CL.MONTHLY_INT_AMT,
    CL.ANNUAL_INT_AMT,
    CL.GRADE,
    CL.LOAN_STATUS
as cus_loan2
FROM 
CUS_LOAN CL INNER JOIN REGION R
ON 
CL.REGION_ID = R.REGION_ID;

-- OUT PUT 1 
-- JOINED 5 TABLE AS 1
-- OUTPUT

SELECT * FROM CUSTOMER_LOAN_DETAILS;  -- OUTPUT 1
-- -------------------------------------------------------------------------------------------------------------
-- QUESTION																	--Aras
/* *find the mismatch details using joins - output 2*/


-- QUERY
-- 1 TABLE (SHEET1)
SELECT * FROM CUSTOMER_INTEREST_ANALYSIS;
-- 2 TABLE (SHEET2)
SELECT * FROM CIBIL_SCORE_STATUS;
-- 3 TABLE (SHEET3)
SELECT * FROM CUSTOMER_INFO;
-- 4 TABLE(COUNTRY_STATE IMPORT FROM FILES)
SELECT * FROM COUNTRY_STATE;
-- 5 TABLE (REGION IMPORT FROM FILES)
SELECT * FROM REGION;


-- TABLE 1 && 2
SELECT * FROM CUSTOMER_INTEREST_ANALYSIS; -- LEFT TABLE 
SELECT * FROM CIBIL_SCORE_STATUS ; -- RIGHT TABLE
-- QUERY
CREATE TABLE NON_MATCH1
(SELECT CI.*,CS.LOAN_AMOUNT_TERM,CS.`CIBIL SCORE`,CS.CIBIL_STATUS
FROM CUSTOMER_INTEREST_ANALYSIS CI LEFT JOIN CIBIL_SCORE_STATUS CS
ON CI.LOAN_ID = CS.LOAN_ID WHERE CS.LOAN_ID IS NULL)
UNION
(SELECT CI.*,CS.LOAN_AMOUNT_TERM,CS.`CIBIL SCORE`,CS.CIBIL_STATUS
FROM CUSTOMER_INTEREST_ANALYSIS CI RIGHT JOIN CIBIL_SCORE_STATUS CS
ON CI.LOAN_ID = CS.LOAN_ID WHERE CI.LOAN_ID IS NULL) ;
-- OUTPUT
SELECT * FROM NON_MATCH1;


-- TABLE 3 && 4
SELECT * FROM COUNTRY_STATE; -- LEFT TABLE
SELECT * FROM CUSTOMER_INFO; -- RIGHT TABLE
-- QUERY
CREATE TABLE NON_MATCH2
(SELECT CU.*,CO.POSTAL_CODE,CO.SEGMENT,CO.STATE
FROM CUSTOMER_INFO CU RIGHT JOIN COUNTRY_STATE CO 
ON CU.LOAN_ID = CO.LOAN_ID WHERE CU.LOAN_ID IS NULL)
UNION
(SELECT CU.*,CO.POSTAL_CODE,CO.SEGMENT,CO.STATE
FROM CUSTOMER_INFO CU LEFT JOIN COUNTRY_STATE CO 
ON CU.LOAN_ID = CO.LOAN_ID WHERE CO.LOAN_ID IS NULL);
-- OUTPUT
SELECT * FROM NON_MATCH2;  


SELECT * FROM NON_MATCH2; -- LEFT TABLE
SELECT * FROM REGION ; -- RIGHT TABLE
-- QUERY -
CREATE TABLE NON_MATCH3;
(SELECT M2.*,R.REGION FROM 
NON_MATCH2 M2 LEFT JOIN REGION R 
ON M2.REGION_ID = R.REGION_ID WHERE R.REGION_ID IS NULL)
UNION
(SELECT M2.*,R.REGION FROM 
NON_MATCH2 M2 RIGHT JOIN REGION R 
ON M2.REGION_ID = R.REGION_ID WHERE M2.REGION_ID IS NULL);

-- OUTPUT
 SELECT * FROM NON_MATCH3;



-- 1&2(NON_MATCH1) || 3&4+5 =(NON_MATCH3)
SELECT * FROM NON_MATCH1; 
SELECT * FROM NON_MATCH3;  


-- OUTPUT 2  -> (USING FULL OUTER JOIN)
SELECT M1.*,M3.* 
FROM 
NON_MATCH1 M1 LEFT JOIN NON_MATCH3 M3
ON 
M1.`CUSTOMER ID` = M3.CUSTOMER_ID WHERE M3.CUSTOMER_ID IS NULL
UNION
SELECT M1.*,M3.* 
FROM 
NON_MATCH1 M1 RIGHT JOIN NON_MATCH3 M3
ON 
M1.`CUSTOMER ID` = M3.CUSTOMER_ID WHERE M1.`CUSTOMER ID` IS NULL;


-- -----------------------------------------------------------------------------------------------------------
-- QUESTION
/*Filtering information using inner join
* Filter high cibil score - output 3*/

-- QUERY && OUTPUT
SELECT * FROM CUSTOMER_LOAN_DETAILS WHERE 
CIBIL_STATUS = "HIGH CIBIL SCORE"; -- OUTPUT 3
-- ------------------------------------------------------------------------------------------------------
-- QUESTION																-- kishore
/* Filter home office and corporate - output 4*/


-- QUERY && OUTPUT
SELECT * FROM CUSTOMER_LOAN_DETAILS WHERE SEGMENT IN
("CORPORATE","HOME OFFICE"); -- OUTPUT 4
-- ---------------------------------------------------------------------------------------------
-- QUESTION																		-- kiran
/*Store all the outputs as procedure*/


-- QUERY
-- PROCEDURE(OUT PUT 1,2,3 AND 4) 
DELIMITER //
CREATE PROCEDURE FILTERED_OUTPUT()
BEGIN 

SELECT * FROM CUSTOMER_LOAN_DETAILS; 

(SELECT M1.*,M3.* 
FROM 
NON_MATCH1 M1 LEFT JOIN NON_MATCH3 M3
ON 
M1.`CUSTOMER ID` = M3.CUSTOMER_ID WHERE M3.CUSTOMER_ID IS NULL
UNION
SELECT M1.*,M3.* 
FROM 
NON_MATCH1 M1 RIGHT JOIN NON_MATCH3 M3
ON 
M1.`CUSTOMER ID` = M3.CUSTOMER_ID WHERE M1.`CUSTOMER ID` IS NULL);

SELECT * FROM CUSTOMER_LOAN_DETAILS WHERE CIBIL_STATUS = "HIGH CIBIL SCORE";
SELECT * FROM CUSTOMER_LOAN_DETAILS WHERE SEGMENT IN ("CORPORATE","HOME OFFICE");
END //
DELIMITER ;
-- FINAL OF OUTPUT PROCEDURE
CALL FILTERED_OUTPUT();   -- ->✅
-- ---------------------------------------------------------------------------------------------------------------------------

-- CTE  - > COMMON TABLE EXPRESSION 
USE LOAN_MANAGEMENT_SYSTEM;
SHOW TABLES;
SELECT * FROM CUSTOMER_INCOME;
SELECT * FROM CUSTOMER_INFO;
--  CTE = temporary view in memory
WITH CTE AS (
    SELECT 
        CI.`CUSTOMER ID`,
        CI.APPLICANTINCOME,
        INFO.CUSTOMER_NAME,
        INFO.GENDER,
        INFO.AGE,
        INFO.MARRIED,
        INFO.EDUCATION,
        INFO.SELF_EMPLOYED,
        INFO.LOAN_ID,
        INFO.REGION_ID
FROM CUSTOMER_INCOME CI
INNER JOIN CUSTOMER_INFO INFO
ON CI.`CUSTOMER ID` = INFO.CUSTOMER_ID
WHERE CI.APPLICANTINCOME > 10000
)
SELECT * FROM CTE;    -- ->✅

-- ----------------------------------------------------------------------------------------------------------------------------
-- ER DIAGRAM
CREATE DATABASE ER_DIAGRAM;
USE ER_DIAGRAM;

-- SECONDARY TABLES -> PARENT TABLE
CREATE TABLE ER_FACT (
    LOAN_ID VARCHAR(20) PRIMARY KEY,
    CONSTRAINT FEK_LOAN FOREIGN KEY(LOAN_ID)REFERENCES LOAN_DIM(LOAN_ID),
    CUSTOMER_ID VARCHAR(20),
    CONSTRAINT FEK_CUS FOREIGN KEY(CUSTOMER_ID)REFERENCES CUSTOMER_DIM(CUSTOMER_ID),
    LOANAMOUNT INT,
    LOAN_AMOUNT_TERM INT,
    CIBIL_SCORE INT,
    REGION_ID INT,
    CONSTRAINT FEK_REG FOREIGN KEY(REGION_ID)REFERENCES REG_DIM(REGION_ID),
    POSTAL_CODE INT,
    CONSTRAINT FEK_CS FOREIGN KEY(POSTAL_CODE)REFERENCES CS_DIM(POSTAL_CODE),
    APPLICANTINCOME INT,
    COAPPLICANTINCOME INT
);


-- PRIMARY TABLES -> CHILD TABLES

CREATE TABLE LOAN_DIM(
LOAN_ID VARCHAR(20) PRIMARY KEY,
CUSTOMER_ID VARCHAR(20),
LOANAMOUNT INT,
LOAN_AMOUNT_TERM INT,
CIBIL_SCORE INT,
APPLICANTINCOME INT,
COAPPLICATINCOME INT,
PROPERTY_AREA INT,
LOAN_STATUS INT);


-- CUS DIM
CREATE TABLE CUSTOMER_DIM(
CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
CUSTOMER_NAME VARCHAR(20),
GENDER VARCHAR(20),
AGE INT,
MARRIED VARCHAR(20),
EDUCATION VARCHAR(20),
SELF_EMPLOYED VARCHAR(20));

-- C&S 
CREATE TABLE CS_DIM(
CUSTOEMR_ID VARCHAR(20),
POSTAL_CODE INT	PRIMARY KEY,
SEGMENT VARCHAR(20),
STATE VARCHAR(20),
REGION_ID INT );

-- REG
CREATE TABLE REG_DIM(
REGION VARCHAR(20),
REGION_ID INT PRIMARY KEY);